import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { getFormatter, getTranslations, setRequestLocale } from "next-intl/server";
import { ArrowLeft } from "lucide-react";
import { ArticleBody } from "@/components/forum/ArticleBody";
import { ArticleToc } from "@/components/forum/ArticleToc";
import { UpdatedAt } from "@/components/forum/UpdatedAt";
import { Link, getPathname } from "@/i18n/navigation";
import { getPostBySlug, getTranslationSlug } from "@/lib/queries/posts";
import { articleToPlainText } from "@/lib/tiptap/render";
import { TOPIC_IDS, TOPIC_TONE, type TopicId } from "@/lib/constants";
import { routing, type Locale } from "@/i18n/routing";

type Params = Promise<{ locale: string; topic: string; slug: string }>;

export async function generateMetadata({
  params,
}: {
  params: Params;
}): Promise<Metadata> {
  const { locale, topic, slug } = await params;
  const post = await getPostBySlug(locale as Locale, slug, "lesson");

  if (!post) return { title: "404" };

  return {
    title: post.title,
    description: post.excerpt ?? articleToPlainText(post.content, 160),
    // Image is generated by the sibling opengraph-image.tsx route.
    openGraph: {
      type: "article",
      title: post.title,
      publishedTime: post.publishedAt ?? undefined,
    },
    alternates: {
      // Same approach as the forum article page: build the path through
      // next-intl's localised routing instead of string concatenation, using
      // the same `getTranslationSlug` lookup as the source of truth so the
      // canonical and the translation link can never disagree. `topic` is not
      // localised (see i18n/routing.ts), so it stays the same across locales.
      canonical: getPathname({
        href: { pathname: "/bai-hoc/[topic]/[slug]", params: { topic, slug: post.slug } },
        locale: locale as Locale,
      }),
      languages: Object.fromEntries(
        await Promise.all(
          routing.locales.map(async (l) => {
            const alt = await getTranslationSlug(post.translationId, l);
            return [
              l,
              alt
                ? getPathname({
                    href: { pathname: "/bai-hoc/[topic]/[slug]", params: { topic, slug: alt } },
                    locale: l,
                  })
                : getPathname({ href: { pathname: "/bai-hoc/[topic]", params: { topic } }, locale: l }),
            ];
          })
        )
      ),
    },
  };
}

export default async function LessonArticlePage({ params }: { params: Params }) {
  const { locale, topic, slug } = await params;
  setRequestLocale(locale);

  if (!TOPIC_IDS.includes(topic as TopicId)) notFound();

  const topicId = topic as TopicId;
  const t = await getTranslations("topics");
  const tLessons = await getTranslations("lessons");
  const format = await getFormatter();

  const post = await getPostBySlug(locale as Locale, slug, "lesson");
  if (!post) notFound();

  const tone = TOPIC_TONE[topicId];

  return (
    <article className="px-5 py-14 md:px-8 md:py-20">
      <div className="mx-auto w-full max-w-3xl">
        <Link
          href={{ pathname: "/bai-hoc/[topic]", params: { topic: topicId } }}
          className="inline-flex items-center gap-1.5 text-sm text-text-muted transition-colors hover:text-accent"
        >
          <ArrowLeft className="size-4" strokeWidth={2.2} />
          {tLessons("backToTopic", { topic: t(`${topicId}.title`) })}
        </Link>

        <header className="mt-8">
          <span
            className="inline-flex rounded-full px-3 py-1 text-xs font-semibold"
            style={{ background: tone.soft, color: tone.text }}
          >
            {t(`${topicId}.title`)}
          </span>

          <h1 className="mt-4 text-balance text-[30px] font-extrabold leading-[1.15] tracking-[-0.03em] text-text md:text-[42px]">
            {post.title}
          </h1>

          {post.publishedAt && (
            <time
              dateTime={post.publishedAt}
              className="mt-5 block text-sm text-text-muted"
            >
              {tLessons("title")} ·{" "}
              {format.dateTime(new Date(post.publishedAt), {
                dateStyle: "long",
              })}
            </time>
          )}

          <UpdatedAt
            publishedAt={post.publishedAt}
            updatedAt={post.updatedAt}
            className="mt-2 block text-sm text-text-muted"
          />
        </header>

        {post.coverImageUrl && (
          <div className="relative mt-8 aspect-video w-full overflow-hidden rounded-2xl">
            <Image
              src={post.coverImageUrl}
              alt=""
              fill
              priority
              sizes="(max-width: 768px) 100vw, 768px"
              className="object-cover"
            />
          </div>
        )}

        <ArticleToc content={post.content} />

        <div className="mt-10">
          <ArticleBody content={post.content} />
        </div>
      </div>
    </article>
  );
}
