import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getFormatter, getTranslations, setRequestLocale } from "next-intl/server";
import { ArticleShell } from "@/components/forum/ArticleShell";
import { UpdatedAt } from "@/components/forum/UpdatedAt";
import { VideoCard } from "@/components/video/VideoCard";
import { articleLanguageAlternates } from "@/lib/article-alternates";
import { getPathname } from "@/i18n/navigation";
import { getPostBySlug, getTranslationSlug, listRelatedVideos } from "@/lib/queries/posts";
import { articleToPlainText } from "@/lib/tiptap/render";
import { TOPIC_IDS, TOPIC_TONE, type TopicId } from "@/lib/constants";
import { routing, type Locale } from "@/i18n/routing";

type Params = Promise<{ locale: string; topic: string; slug: string }>;

export async function generateMetadata({
  params,
}: {
  params: Params;
}): Promise<Metadata> {
  const { locale, topic, slug } = await params;
  const post = await getPostBySlug(locale as Locale, slug, "lesson");

  if (!post) return { title: "404" };

  const description = post.excerpt || articleToPlainText(post.content, 160) || undefined;

  return {
    title: post.title,
    description,
    // Image is generated by the sibling opengraph-image.tsx route.
    openGraph: {
      type: "article",
      title: post.title,
      publishedTime: post.publishedAt ?? undefined,
    },
    alternates: {
      // Same approach as the forum article page: build the path through
      // next-intl's localised routing instead of string concatenation, using
      // the same `getTranslationSlug` lookup as the source of truth so the
      // canonical and the translation link can never disagree. `topic` is not
      // localised (see i18n/routing.ts), so it stays the same across locales.
      canonical: getPathname({
        href: { pathname: "/bai-hoc/[topic]/[slug]", params: { topic, slug: post.slug } },
        locale: locale as Locale,
      }),
      languages: articleLanguageAlternates(
        Object.fromEntries(
          await Promise.all(
            routing.locales.map(async (l) => {
              const alt = await getTranslationSlug(post.translationId, l);
              return [
                l,
                alt
                  ? getPathname({
                      href: { pathname: "/bai-hoc/[topic]/[slug]", params: { topic, slug: alt } },
                      locale: l,
                    })
                  : null,
              ];
            })
          )
        ),
        routing.defaultLocale
      ),
    },
  };
}

export default async function LessonArticlePage({ params }: { params: Params }) {
  const { locale, topic, slug } = await params;
  setRequestLocale(locale);

  if (!TOPIC_IDS.includes(topic as TopicId)) notFound();

  const topicId = topic as TopicId;
  const t = await getTranslations("topics");
  const tLessons = await getTranslations("lessons");
  const format = await getFormatter();

  const post = await getPostBySlug(locale as Locale, slug, "lesson");
  if (!post) notFound();

  const tone = TOPIC_TONE[topicId];
  const [relatedVideos, tVideos] = await Promise.all([
    listRelatedVideos(locale as Locale, post.translationId),
    getTranslations("videos"),
  ]);

  return (
    <ArticleShell
      back={{
        href: { pathname: "/bai-hoc/[topic]", params: { topic: topicId } },
        label: tLessons("backToTopic", { topic: t(`${topicId}.title`) }),
      }}
      headerExtra={
        <span
          className="inline-flex rounded-full px-3 py-1 text-xs font-semibold"
          style={{ background: tone.soft, color: tone.text }}
        >
          {t(`${topicId}.title`)}
        </span>
      }
      title={post.title}
      meta={
        <>
          {post.publishedAt && (
            <time dateTime={post.publishedAt}>
              {tLessons("title")} ·{" "}
              {format.dateTime(new Date(post.publishedAt), { dateStyle: "long" })}
            </time>
          )}
          <UpdatedAt publishedAt={post.publishedAt} updatedAt={post.updatedAt} />
        </>
      }
      coverImageUrl={post.coverImageUrl}
      content={post.content}
      locale={locale as Locale}
      postId={post.id}
      footer={
        relatedVideos.length > 0 && (
          <section aria-labelledby="related-videos" className="mt-16 border-t border-border pt-10">
            <h2 id="related-videos" className="text-lg font-bold tracking-[-0.01em] text-text">
              {tVideos("related")}
            </h2>
            <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {relatedVideos.map((video) => (
                <VideoCard key={video.id} post={video} compact />
              ))}
            </div>
          </section>
        )
      }
    />
  );
}
